### ISSUE TITLE
Install and run test on MacOS

### ISSUE THREAD

**Issue by emiljzak** [CFEL-CMI/richmol#19] opened 2021-06-25 06:40 UTC
Missing info on how to actually _run_ richmol calculations. Install by `pip install --upgrade git+https://github.com/CFEL-CMI/richmol.git` fails. See log: https://github.com/CFEL-CMI/richmol/blob/develop/tests/beta-tests/richmol_install_log.txt

**Comment by yachmena** [comment] 2021-06-25 07:04
Hi @emiljzak, you problem seems to be in gcc compiler with conda. May be try `conda install llvm`, `conda install gcc`, and `conda install libgcc`. You can put your logs directly here, no need to keep them in the repository

**Comment by yachmena** [comment] 2021-06-25 07:11
Regarding your comment _how to run_, please use it as standard a python module, e.g., `python3 -c "from richmol.rot import Molecule; water = Molecule()"`

**Comment by emiljzak** [comment] 2021-06-25 07:20
@yachmena:  conda install llvm | conda install gcc | conda install libgcc done and still fails:

[richmol.log](https://github.com/CFEL-CMI/richmol/files/6714297/richmol.log)

**Comment by yachmena** [comment] 2021-06-25 07:38
@emiljzak , found similar issue and solution [here](https://github.com/bluesheeptoken/CPT/issues/68#issuecomment-563342866)
Apparently `llvm` does not support `-fopenmp`, solution is to use brew's `llvm`. Please let me know if it works and I will add this workaround to the installation instructions

**Comment by emiljzak** [comment] 2021-07-09 12:01
The issue with -fopenmp can be solved with steps shown [here](https://stackoverflow.com/questions/28970935/osx-replace-gcc-version-4-2-1-with-4-9-installed-via-homebrew/28982564#28982564). 
One must make sure that $PATH contains /usr/local/bin before /usr/bin/. Homebrew's gcc is installed by default in the former directory. Modify .bash_profile with export PATH=/usr/local/bin:$PATH. Check with gcc --version to make sure clang's llvm is not used. Alternatively create symbolic link from /usr/bin/gcc to /usr/local/bin/gcc-xx, where xx is version ID. 

Still, further errors turn up: 
[setup_err.txt](https://github.com/CFEL-CMI/richmol/files/6791128/setup_err.txt)
[setup_out.txt](https://github.com/CFEL-CMI/richmol/files/6791130/setup_out.txt)

**Comment by jokuha** [comment] 2021-07-09 14:54
Should NOT, never, create a link in /usr/bin – that is reserved for system files.
The better use an shell alias 'gcc' to specify the appropriate version...

**Comment by yachmena** [comment] 2021-07-29 08:21
@emiljzak, which version of macos do you use? brew's gcc is broken on macOS 10.14. This can be solved by replacing `gcc` with `gcc@9` (`brew remove g++` and `brew install g++@9`) or upgrade macos

**Comment by yachmena** [comment] 2021-07-29 21:10
@emiljzak, I tired to install richmol on macos Big Sur, the problem is with compiling C code generated by f2py. First, there was an error `limits.h` missing. So I updated XCode developer tools by running `xcode-select --install`, which in my case refused to update until I deleted them `sudo rm -rf /Library/Developer/CommandLineTools`. The error persisted, then I set C compiler `sysroot` to /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk by adding a line `export CFLAGS="-isysroot '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk' ${CFLAGS}"` to `~/.profile file`. Now I am getting an error `fatal error: threads.h: No such file or directory`. Stuck here

I suggest we close this as it is not a richmol issue.

**Closed as completed** 2021-07-29 21:11 UTC
Labels: bug, documentation

**Comment by emiljzak** [comment] 2021-07-30 05:54
> @emiljzak, which version of macos do you use? brew's gcc is broken on macOS 10.14. This can be solved by replacing `gcc` with `gcc@9` (`brew remove g++` and `brew install g++@9`) or upgrade macos

@yachmena , I'm using macOS 10.14, which seems to be the issue. Changing gcc doesn't help either. Apparently not every operating system has grown up enough to discover the wonders of Richmol. Now switched to linux mint.
